import { Card, AssetSymbol, CardRarity, FoilType } from "@/types";

export const BASE_CARD_CATALOG: Card[] = [
  {
    id: "card-btc-legendary",
    tokenId: 1,
    assetSymbol: "BTC",
    name: "Satoshi's Genesis",
    subtitle: "The Immutable Apex",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 160,
    baseDef: 175,
    baseSpd: 85,
    currentAtk: 160,
    currentDef: 175,
    currentSpd: 85,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "The cryptographic spark that ignited a decentralized epoch. High defense and devastating momentum.",
    skill: {
      name: "God Candle Megaburn",
      description: "Infuses 170 Fire damage and sets the opponent on fire (Burn for 2 turns).",
      manaCost: 35,
      type: "burn",
      element: "fire",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 12,
    owner: "0x71C...Demo",
    sparkline: [63200, 63800, 64200, 64900, 65420]
  },
  {
    id: "card-eth-legendary",
    tokenId: 2,
    assetSymbol: "ETH",
    name: "Turing Sovereign",
    subtitle: "World Computer Engine",
    category: "L1",
    rarity: "Legendary",
    foilType: "Holo",
    baseAtk: 145,
    baseDef: 155,
    baseSpd: 110,
    currentAtk: 145,
    currentDef: 155,
    currentSpd: 110,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Programmable liquidity incarnate. Synthesizes gas barriers and executes atomic bytecode strikes.",
    skill: {
      name: "Cold Storage Freeze",
      description: "Blasts target for 145 Ice damage and Freezes them solid, skipping their next turn.",
      manaCost: 35,
      type: "freeze",
      element: "ice",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 10,
    owner: "0x71C...Demo",
    sparkline: [3380, 3420, 3450, 3460, 3480]
  },
  {
    id: "card-sol-epic",
    tokenId: 3,
    assetSymbol: "SOL",
    name: "Turbine Speedster",
    subtitle: "High Throughput Velocity",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 138,
    baseDef: 95,
    baseSpd: 170,
    currentAtk: 138,
    currentDef: 95,
    currentSpd: 170,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Blistering proof-of-history validator that outpaces any opponent turn before the block expires.",
    skill: {
      name: "Overclocked Lightning",
      description: "Strikes with 155 Electric damage, inflicting Shock (-50% SPD and 35% recoil fizzle).",
      manaCost: 30,
      type: "shock",
      element: "electric",
      cooldownTurns: 1
    },
    mintedAt: Date.now() - 86400000 * 7,
    owner: "0x71C...Demo",
    sparkline: [142, 145, 149, 150, 152.8]
  },
  {
    id: "card-link-epic",
    tokenId: 4,
    assetSymbol: "LINK",
    name: "Oracle Sovereign",
    subtitle: "Consensus Truth Sentinel",
    category: "Infrastructure",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 115,
    baseDef: 140,
    baseSpd: 105,
    currentAtk: 115,
    currentDef: 140,
    currentSpd: 105,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Cryptographic bridge verifying cross-chain reality. Immune to deceptive market anomalies.",
    skill: {
      name: "DON Consensus",
      description: "Fortifies all team cards by +25% DEF and restores 100 HP.",
      manaCost: 30,
      type: "shield",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 5,
    owner: "0x71C...Demo",
    sparkline: [13.9, 14.1, 14.3, 14.5, 14.6]
  },
  {
    id: "card-doge-rare",
    tokenId: 5,
    assetSymbol: "DOGE",
    name: "Kabosu's Bark",
    subtitle: "Meme Vanguard",
    category: "Meme",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 95,
    baseDef: 85,
    baseSpd: 120,
    currentAtk: 95,
    currentDef: 85,
    currentSpd: 120,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Much wow, very volatility. Can trigger an unexpected viral rally out of nowhere.",
    skill: {
      name: "Solar Flare Bark",
      description: "Blasts fiery meme hype for 140 damage and sets the opponent on Fire (Burn for 2 turns).",
      manaCost: 25,
      type: "burn",
      element: "fire",
      cooldownTurns: 1
    },
    mintedAt: Date.now() - 86400000 * 4,
    owner: "0x71C...Demo",
    sparkline: [0.141, 0.139, 0.138, 0.137, 0.138]
  },
  {
    id: "card-avax-rare",
    tokenId: 6,
    assetSymbol: "AVAX",
    name: "Subnet Blizzard",
    subtitle: "Avalanche Engine",
    category: "L1",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 102,
    baseDef: 110,
    baseSpd: 100,
    currentAtk: 102,
    currentDef: 110,
    currentSpd: 100,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Parallel subnet architecture delivering rapid freezing blows.",
    skill: {
      name: "Absolute Zero Blizzard",
      description: "Unleashes an icy avalanche dealing 140 Ice damage and Freezes target for 1 turn.",
      manaCost: 30,
      type: "freeze",
      element: "ice",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [27.8, 28.3, 28.9, 29.1, 29.4]
  },
  {
    id: "card-bnb-epic",
    tokenId: 7,
    assetSymbol: "BNB",
    name: "Treasury Vault",
    subtitle: "Exchange Citadel",
    category: "L1",
    rarity: "Epic",
    foilType: "Standard",
    baseAtk: 125,
    baseDef: 135,
    baseSpd: 90,
    currentAtk: 125,
    currentDef: 135,
    currentSpd: 90,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Unmatched ecosystem utility and auto-burn mechanics that incinerate enemy defenses.",
    skill: {
      name: "Quarterly Incinerate",
      description: "Burns enemy reserves for 160 Fire damage and inflicts severe Burn for 2 turns.",
      manaCost: 30,
      type: "burn",
      element: "fire",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 2,
    owner: "0x71C...Demo",
    sparkline: [578, 580, 582, 583, 585]
  },
  {
    id: "card-pepe-rare",
    tokenId: 8,
    assetSymbol: "PEPE",
    name: "Liquidity Frog",
    subtitle: "Viral Degeneracy",
    category: "Meme",
    rarity: "Rare",
    foilType: "Holo",
    baseAtk: 118,
    baseDef: 70,
    baseSpd: 125,
    currentAtk: 118,
    currentDef: 70,
    currentSpd: 125,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Pure unadulterated degen momentum. Spikes violently when the frog awakens.",
    skill: {
      name: "Meme Toxic Cloud",
      description: "Sprays toxic swamp fog for 130 Poison damage, inflicting escalating Toxic Poison for 2 turns.",
      manaCost: 25,
      type: "poison",
      element: "poison",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 1,
    owner: "0x71C...Demo",
    sparkline: [0.0000081, 0.0000085, 0.0000091, 0.0000094]
  },
  {
    id: "card-near-common",
    tokenId: 9,
    assetSymbol: "NEAR",
    name: "Sharded Weaver",
    subtitle: "User-Friendly Compute",
    category: "L1",
    rarity: "Common",
    foilType: "Standard",
    baseAtk: 80,
    baseDef: 85,
    baseSpd: 90,
    currentAtk: 80,
    currentDef: 85,
    currentSpd: 90,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Reliable, accessible sharding layer for decentralized applications.",
    skill: {
      name: "Account Abstraction",
      description: "Generates 20 extra mana and cleanses 1 debuff.",
      manaCost: 15,
      type: "buff",
      cooldownTurns: 1
    },
    mintedAt: Date.now() - 86400000 * 8,
    owner: "0x71C...Demo",
    sparkline: [5.2, 5.1, 5.0, 4.98, 4.95]
  },
  {
    id: "card-sui-rare",
    tokenId: 10,
    assetSymbol: "SUI",
    name: "Move Sentinel",
    subtitle: "Object-Centric Vanguard",
    category: "L1",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 108,
    baseDef: 92,
    baseSpd: 130,
    currentAtk: 108,
    currentDef: 92,
    currentSpd: 130,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Parallel execution model designed for instant settlement and dynamic NFT state.",
    skill: {
      name: "Glacial Freeze Tide",
      description: "Strikes with 140 Ice damage and Freezes the opponent solid for 1 turn.",
      manaCost: 30,
      type: "freeze",
      element: "ice",
      cooldownTurns: 2
    },
    mintedAt: Date.now() - 86400000 * 2,
    owner: "0x71C...Demo",
    sparkline: [1.68, 1.72, 1.77, 1.81, 1.84]
  },
  {
    id: "card-btc-epic",
    tokenId: 11,
    assetSymbol: "BTC",
    name: "Halving Citadel",
    subtitle: "Deflationary Bastion",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 140,
    baseDef: 160,
    baseSpd: 75,
    currentAtk: 140,
    currentDef: 160,
    currentSpd: 75,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Hardened security backed by mathematical scarcity.",
    skill: { name: "Difficulty Adjustment", description: "Increases DEF by 35% for 2 turns.", manaCost: 25, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 15,
    owner: "0x71C...Demo",
    sparkline: [62000, 63100, 64200, 64800, 65420]
  },
  {
    id: "card-btc-rare",
    tokenId: 12,
    assetSymbol: "BTC",
    name: "Taproot Inscription",
    subtitle: "Cryptographic Artifact",
    category: "L1",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 115,
    baseDef: 120,
    baseSpd: 90,
    currentAtk: 115,
    currentDef: 120,
    currentSpd: 90,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Permanent digital runes inscribed directly onto the foundational layer.",
    skill: { name: "Ordinal Engraving", description: "Deals 1.4x ATK and gains 10 mana.", manaCost: 20, type: "attack", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 18,
    owner: "0x71C...Demo",
    sparkline: [61000, 62400, 63800, 64500, 65420]
  },
  {
    id: "card-btc-common",
    tokenId: 13,
    assetSymbol: "BTC",
    name: "PoW Node Sentinel",
    subtitle: "Distributed Verifier",
    category: "L1",
    rarity: "Common",
    foilType: "Standard",
    baseAtk: 90,
    baseDef: 110,
    baseSpd: 80,
    currentAtk: 90,
    currentDef: 110,
    currentSpd: 80,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Silently validating hashes across thousands of peer nodes.",
    skill: { name: "Block Relay", description: "Cleanses 1 debuff and restores 20 shield.", manaCost: 15, type: "shield", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 20,
    owner: "0x71C...Demo",
    sparkline: [60000, 61500, 63000, 64200, 65420]
  },
  {
    id: "card-eth-epic",
    tokenId: 14,
    assetSymbol: "ETH",
    name: "Beacon Validator",
    subtitle: "Proof-of-Stake Guardian",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 130,
    baseDef: 140,
    baseSpd: 115,
    currentAtk: 130,
    currentDef: 140,
    currentSpd: 115,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Attests to canonical block roots every 12 seconds with cryptographic finality.",
    skill: { name: "Slashing Penalty", description: "Deals 1.8x ATK and depletes 25 enemy energy.", manaCost: 30, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 14,
    owner: "0x71C...Demo",
    sparkline: [3300, 3350, 3410, 3450, 3480]
  },
  {
    id: "card-eth-gold",
    tokenId: 15,
    assetSymbol: "ETH",
    name: "ZK Rollup Architect",
    subtitle: "Succinct Proof Matrix",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 155,
    baseDef: 150,
    baseSpd: 125,
    currentAtk: 155,
    currentDef: 150,
    currentSpd: 125,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Compresses thousands of state transitions into a single mathematical truth.",
    skill: { name: "STARK Verifier", description: "Bypasses 50% enemy DEF and delivers a devastating crit.", manaCost: 40, type: "attack", cooldownTurns: 3 },
    mintedAt: Date.now() - 86400000 * 11,
    owner: "0x71C...Demo",
    sparkline: [3200, 3320, 3400, 3440, 3480]
  },
  {
    id: "card-eth-rare",
    tokenId: 16,
    assetSymbol: "ETH",
    name: "Blob Weaver",
    subtitle: "Dencun Data Courier",
    category: "L1",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 110,
    baseDef: 105,
    baseSpd: 135,
    currentAtk: 110,
    currentDef: 105,
    currentSpd: 135,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Transports ephemeral blobspace carrying high-capacity L2 settlement.",
    skill: { name: "Proto-Danksharding", description: "Boosts SPD by 40% and grants an extra dodge chance.", manaCost: 20, type: "buff", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 6,
    owner: "0x71C...Demo",
    sparkline: [3250, 3310, 3380, 3440, 3480]
  },
  {
    id: "card-sol-legendary",
    tokenId: 17,
    assetSymbol: "SOL",
    name: "Firedancer Vanguard",
    subtitle: "Million-TPS Engine",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 165,
    baseDef: 100,
    baseSpd: 185,
    currentAtk: 165,
    currentDef: 100,
    currentSpd: 185,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Rewritten in pure C for hardware-limit throughput and sub-millisecond execution.",
    skill: { name: "Hardware Overclock", description: "Strikes 3 times in 1 turn with 70% ATK each.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 5,
    owner: "0x71C...Demo",
    sparkline: [135, 141, 146, 149, 152.8]
  },
  {
    id: "card-sol-rare",
    tokenId: 18,
    assetSymbol: "SOL",
    name: "Sealevel Parallelizer",
    subtitle: "Concurrent State Weaver",
    category: "L1",
    rarity: "Rare",
    foilType: "Holo",
    baseAtk: 122,
    baseDef: 90,
    baseSpd: 155,
    currentAtk: 122,
    currentDef: 90,
    currentSpd: 155,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Processes thousands of smart contract reads and writes across non-overlapping accounts simultaneously.",
    skill: { name: "Parallel Execution", description: "Deals 1.5x damage and resets cooldown of another skill.", manaCost: 25, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 9,
    owner: "0x71C...Demo",
    sparkline: [138, 142, 147, 150, 152.8]
  },
  {
    id: "card-link-legendary",
    tokenId: 19,
    assetSymbol: "LINK",
    name: "CCIP Nexus Bridge",
    subtitle: "Cross-Chain Interop Sovereign",
    category: "Infrastructure",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 145,
    baseDef: 165,
    baseSpd: 120,
    currentAtk: 145,
    currentDef: 165,
    currentSpd: 120,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "The universal messaging standard connecting every blockchain and traditional finance rail.",
    skill: { name: "Cross-Chain Synchrony", description: "Reflects 50% of incoming damage back to attacker.", manaCost: 35, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 8,
    owner: "0x71C...Demo",
    sparkline: [13.2, 13.8, 14.1, 14.4, 14.6]
  },
  {
    id: "card-link-rare",
    tokenId: 20,
    assetSymbol: "LINK",
    name: "DECO Privacy Sentinel",
    subtitle: "Zero-Knowledge Web Oracle",
    category: "Infrastructure",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 110,
    baseDef: 125,
    baseSpd: 110,
    currentAtk: 110,
    currentDef: 125,
    currentSpd: 110,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Proves off-chain credentials and bank balances without revealing raw private data.",
    skill: { name: "Zero-Knowledge Veil", description: "Makes card untargetable for 1 turn.", manaCost: 25, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 13,
    owner: "0x71C...Demo",
    sparkline: [13.5, 13.9, 14.2, 14.5, 14.6]
  },
  {
    id: "card-doge-legendary",
    tokenId: 21,
    assetSymbol: "DOGE",
    name: "Kabosu Eternal",
    subtitle: "The Ancestral Meme Queen",
    category: "Meme",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 150,
    baseDef: 140,
    baseSpd: 130,
    currentAtk: 150,
    currentDef: 140,
    currentSpd: 130,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Her kind gaze conquered global culture and made laughter the purest store of value.",
    skill: { name: "Bark to the Moon", description: "Inflicts 2.0x damage and confuses opponent for 2 turns.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 16,
    owner: "0x71C...Demo",
    sparkline: [0.12, 0.128, 0.132, 0.135, 0.138]
  },
  {
    id: "card-doge-epic",
    tokenId: 22,
    assetSymbol: "DOGE",
    name: "Much Wow Shibe",
    subtitle: "Viral Frenzy Catalyst",
    category: "Meme",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 125,
    baseDef: 115,
    baseSpd: 120,
    currentAtk: 125,
    currentDef: 115,
    currentSpd: 120,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Such decentralized. Very ledger. Much battle power.",
    skill: { name: "Tip Frenzy", description: "Heals all active allies for 30 HP.", manaCost: 25, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 11,
    owner: "0x71C...Demo",
    sparkline: [0.125, 0.13, 0.134, 0.136, 0.138]
  },
  {
    id: "card-avax-legendary",
    tokenId: 23,
    assetSymbol: "AVAX",
    name: "Snowman Sovereign",
    subtitle: "Metastable Consensus Core",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 150,
    baseDef: 145,
    baseSpd: 135,
    currentAtk: 150,
    currentDef: 145,
    currentSpd: 135,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Sub-second probabilistic sampling creates an unbreakable crystalline consensus.",
    skill: { name: "Glacial Avalanche", description: "Deals 2.1x ATK and freezes opponent for 1 turn.", manaCost: 35, type: "attack", cooldownTurns: 3 },
    mintedAt: Date.now() - 86400000 * 7,
    owner: "0x71C...Demo",
    sparkline: [27.0, 27.8, 28.5, 29.0, 29.4]
  },
  {
    id: "card-avax-rare",
    tokenId: 24,
    assetSymbol: "AVAX",
    name: "Teleporter Warp",
    subtitle: "Subnet Messaging Beam",
    category: "L1",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 115,
    baseDef: 105,
    baseSpd: 140,
    currentAtk: 115,
    currentDef: 105,
    currentSpd: 140,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Zero-latency cross-subnet asset bridging powered by Avalanche Warp Messaging.",
    skill: { name: "Subnet Jump", description: "Evades next 2 enemy attacks completely.", manaCost: 25, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 10,
    owner: "0x71C...Demo",
    sparkline: [26.8, 27.5, 28.4, 29.1, 29.4]
  },
  {
    id: "card-bnb-legendary",
    tokenId: 25,
    assetSymbol: "BNB",
    name: "Burn Archon",
    subtitle: "Auto-Burn Megastructure",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 158,
    baseDef: 150,
    baseSpd: 110,
    currentAtk: 158,
    currentDef: 150,
    currentSpd: 110,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Quarterly incinerator that permanently removes supply from existence.",
    skill: { name: "Incinerate", description: "Deals 2.4x ATK damage; permanently lowers target ATK by 20%.", manaCost: 40, type: "attack", cooldownTurns: 3 },
    mintedAt: Date.now() - 86400000 * 14,
    owner: "0x71C...Demo",
    sparkline: [565, 572, 578, 582, 585]
  },
  {
    id: "card-bnb-epic",
    tokenId: 26,
    assetSymbol: "BNB",
    name: "Greenfield Vault",
    subtitle: "Decentralized Data Matrix",
    category: "Infrastructure",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 120,
    baseDef: 145,
    baseSpd: 105,
    currentAtk: 120,
    currentDef: 145,
    currentSpd: 105,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Decentralized storage infrastructure with integrated Web3 smart-contract programmability.",
    skill: { name: "Data Armor", description: "Grants 50 Shield to this card and 25 to allies.", manaCost: 30, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 17,
    owner: "0x71C...Demo",
    sparkline: [560, 570, 575, 580, 585]
  },
  {
    id: "card-pepe-legendary",
    tokenId: 27,
    assetSymbol: "PEPE",
    name: "Frog Sovereign",
    subtitle: "Lord of the Green Candles",
    category: "Meme",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 175,
    baseDef: 85,
    baseSpd: 160,
    currentAtk: 175,
    currentDef: 85,
    currentSpd: 160,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Spawns giant 100% green candle wicks out of nowhere.",
    skill: { name: "Gigapump", description: "Rolls a dice: 70% chance of 3.0x damage, 30% chance of self-stun.", manaCost: 30, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 4,
    owner: "0x71C...Demo",
    sparkline: [0.0000078, 0.0000084, 0.0000089, 0.0000092, 0.0000094]
  },
  {
    id: "card-pepe-epic",
    tokenId: 28,
    assetSymbol: "PEPE",
    name: "Rare Pepe Matrix",
    subtitle: "Immutable Frog Collectible",
    category: "Meme",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 135,
    baseDef: 95,
    baseSpd: 140,
    currentAtk: 135,
    currentDef: 95,
    currentSpd: 140,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Originating on Bitcoin Counterparty in 2016, the earliest cryptographic art meme.",
    skill: { name: "Meme Resonance", description: "Steals 20% ATK from the strongest enemy card.", manaCost: 25, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 8,
    owner: "0x71C...Demo",
    sparkline: [0.000008, 0.0000085, 0.0000088, 0.0000091, 0.0000094]
  },
  {
    id: "card-near-legendary",
    tokenId: 29,
    assetSymbol: "NEAR",
    name: "Chain Signatures Oracle",
    subtitle: "Omnichain Account Controller",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 148,
    baseDef: 142,
    baseSpd: 130,
    currentAtk: 148,
    currentDef: 142,
    currentSpd: 130,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Signs transactions on Bitcoin, Ethereum, and Cosmos directly from a single Near account.",
    skill: { name: "Universal Signing", description: "Copies the skill of any opponent card on field.", manaCost: 35, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 9,
    owner: "0x71C...Demo",
    sparkline: [4.6, 4.75, 4.85, 4.90, 4.95]
  },
  {
    id: "card-near-epic",
    tokenId: 30,
    assetSymbol: "NEAR",
    name: "Rainbow Bridge Colossus",
    subtitle: "Trustless Relayer",
    category: "Infrastructure",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 125,
    baseDef: 135,
    baseSpd: 110,
    currentAtk: 125,
    currentDef: 135,
    currentSpd: 110,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "100% cryptographic trustless bridge connecting Ethereum and Near.",
    skill: { name: "Light Client Verify", description: "Absorbs incoming attack and converts 50% into Mana.", manaCost: 25, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 12,
    owner: "0x71C...Demo",
    sparkline: [4.5, 4.65, 4.78, 4.88, 4.95]
  },
  {
    id: "card-sui-legendary",
    tokenId: 31,
    assetSymbol: "SUI",
    name: "Mysticeti Consensus",
    subtitle: "Sub-300ms Settlement Engine",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 155,
    baseDef: 130,
    baseSpd: 165,
    currentAtk: 155,
    currentDef: 130,
    currentSpd: 165,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Lowest latency Byzantine Fault Tolerant protocol in production blockchain history.",
    skill: { name: "Sub-Second Finality", description: "Takes an immediate extra turn without ending round.", manaCost: 40, type: "buff", cooldownTurns: 3 },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [1.60, 1.68, 1.74, 1.80, 1.84]
  },
  {
    id: "card-sui-epic",
    tokenId: 32,
    assetSymbol: "SUI",
    name: "Sui Water Spirit",
    subtitle: "Dynamic Object Shaper",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 130,
    baseDef: 115,
    baseSpd: 145,
    currentAtk: 130,
    currentDef: 115,
    currentSpd: 145,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Flows like water through parallel transactions without bottlenecks.",
    skill: { name: "Tidal Surge", description: "Attacks all 3 opponent cards for 60% ATK each.", manaCost: 30, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 6,
    owner: "0x71C...Demo",
    sparkline: [1.62, 1.70, 1.76, 1.81, 1.84]
  },
  {
    id: "card-polygon-legendary",
    tokenId: 33,
    assetSymbol: "POLYGON",
    name: "AggLayer Sovereign",
    subtitle: "Unified Liquidity Nexus",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 152,
    baseDef: 155,
    baseSpd: 125,
    currentAtk: 152,
    currentDef: 155,
    currentSpd: 125,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Synthesizes thousands of sovereign ZK-chains into a seamless single blockchain experience.",
    skill: { name: "Aggregated ZK Proof", description: "Bypasses all shields and deals 2.0x direct damage.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 7,
    owner: "0x71C...Demo",
    sparkline: [0.38, 0.39, 0.40, 0.41, 0.42]
  },
  {
    id: "card-polygon-epic",
    tokenId: 34,
    assetSymbol: "POLYGON",
    name: "zkEVM Colossus",
    subtitle: "Bytecode Equivalence Engine",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 134,
    baseDef: 138,
    baseSpd: 115,
    currentAtk: 134,
    currentDef: 138,
    currentSpd: 115,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Complete opcode compatibility with mathematically provable validity proofs.",
    skill: { name: "Proof Verification", description: "Grants 40 Shield and reduces next damage taken by 50%.", manaCost: 25, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 10,
    owner: "0x71C...Demo",
    sparkline: [0.39, 0.40, 0.41, 0.415, 0.42]
  },
  {
    id: "card-arbitrum-legendary",
    tokenId: 35,
    assetSymbol: "ARBITRUM",
    name: "Stylus Rust Juggernaut",
    subtitle: "Multi-VM Heavyweight",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 162,
    baseDef: 148,
    baseSpd: 130,
    currentAtk: 162,
    currentDef: 148,
    currentSpd: 130,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Compiles Rust and C++ down to native WASM execution alongside standard EVM contracts.",
    skill: { name: "Rust Toxic Memory Leak", description: "Injects corrupted bytecodes dealing 135 Poison damage and inflicting Toxic Poison for 2 turns.", manaCost: 30, type: "poison", element: "poison", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 5,
    owner: "0x71C...Demo",
    sparkline: [0.50, 0.51, 0.52, 0.53, 0.54]
  },
  {
    id: "card-arbitrum-epic",
    tokenId: 36,
    assetSymbol: "ARBITRUM",
    name: "Nitro Turbo Rollup",
    subtitle: "High-Throughput Settlement",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 135,
    baseDef: 125,
    baseSpd: 145,
    currentAtk: 135,
    currentDef: 125,
    currentSpd: 145,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Geth-in-WASM architecture providing 10x lower fees and high interactive fraud proofs.",
    skill: { name: "Interactive Fraud Proof", description: "Cancels opponent's last buff and steals 20 mana.", manaCost: 25, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 8,
    owner: "0x71C...Demo",
    sparkline: [0.51, 0.52, 0.525, 0.535, 0.54]
  },
  {
    id: "card-optimism-legendary",
    tokenId: 37,
    assetSymbol: "OPTIMISM",
    name: "Superchain Archon",
    subtitle: "The Interoperable Federation",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 154,
    baseDef: 150,
    baseSpd: 130,
    currentAtk: 154,
    currentDef: 150,
    currentSpd: 130,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Unifying Base, Zora, Mode, and OP Mainnet under shared sequencing and security.",
    skill: { name: "Superchain Alliance", description: "Deals 2.0x damage and buffs team ATK by 25%.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 9,
    owner: "0x71C...Demo",
    sparkline: [1.38, 1.40, 1.42, 1.44, 1.45]
  },
  {
    id: "card-optimism-epic",
    tokenId: 38,
    assetSymbol: "OPTIMISM",
    name: "Fault Proof Enforcer",
    subtitle: "Cannon VM Arbiter",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 128,
    baseDef: 140,
    baseSpd: 120,
    currentAtk: 128,
    currentDef: 140,
    currentSpd: 120,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Executes single-step MIPS instructions on-chain to adjudicate disputed state roots.",
    skill: { name: "Cannon Frostlock", description: "Executes an immutable freeze proof dealing 140 Ice damage and Freezing the target solid for 1 turn.", manaCost: 30, type: "freeze", element: "ice", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 11,
    owner: "0x71C...Demo",
    sparkline: [1.39, 1.41, 1.43, 1.44, 1.45]
  },
  {
    id: "card-base-legendary",
    tokenId: 39,
    assetSymbol: "BASE",
    name: "Onchain Summer Sovereign",
    subtitle: "Mass Adoption Citadel",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 158,
    baseDef: 145,
    baseSpd: 140,
    currentAtk: 158,
    currentDef: 145,
    currentSpd: 140,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Incubated by Coinbase to bring the next billion users into the crypto economy.",
    skill: { name: "Blue Dot Lightning Surge", description: "Discharges 150 Electric damage and inflicts Shock on target for 2 turns.", manaCost: 30, type: "shock", element: "electric", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [1.95, 2.00, 2.04, 2.08, 2.10]
  },
  {
    id: "card-base-epic",
    tokenId: 40,
    assetSymbol: "BASE",
    name: "Aerodrome Slipstream",
    subtitle: "Central Liquidity Hub",
    category: "DeFi",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 132,
    baseDef: 128,
    baseSpd: 138,
    currentAtk: 132,
    currentDef: 128,
    currentSpd: 138,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Automated market maker channeling billions in daily volume across Base.",
    skill: { name: "Liquidity Vortex", description: "Steals 25 energy and converts it into +25 ATK.", manaCost: 25, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 6,
    owner: "0x71C...Demo",
    sparkline: [1.98, 2.02, 2.05, 2.08, 2.10]
  },
  {
    id: "card-cardano-legendary",
    tokenId: 41,
    assetSymbol: "CARDANO",
    name: "Ouroboros Chronos",
    subtitle: "Peer-Reviewed Consensus",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 144,
    baseDef: 170,
    baseSpd: 100,
    currentAtk: 144,
    currentDef: 170,
    currentSpd: 100,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Formally verified cryptography built on decades of academic computer science rigor.",
    skill: { name: "Formal Verification", description: "Immune to all debuffs and gains 40 Shield for 2 turns.", manaCost: 30, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 13,
    owner: "0x71C...Demo",
    sparkline: [0.34, 0.345, 0.35, 0.355, 0.36]
  },
  {
    id: "card-cardano-epic",
    tokenId: 42,
    assetSymbol: "CARDANO",
    name: "Hydra Head Channel",
    subtitle: "Isomorphic State Engine",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 130,
    baseDef: 145,
    baseSpd: 125,
    currentAtk: 130,
    currentDef: 145,
    currentSpd: 125,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Off-chain layer 2 heads executing fast settlements with identical smart-contract semantics.",
    skill: { name: "Multi-Head Strike", description: "Hits twice for 75% damage and resets turn meter.", manaCost: 25, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 15,
    owner: "0x71C...Demo",
    sparkline: [0.345, 0.35, 0.355, 0.358, 0.36]
  },
  {
    id: "card-polkadot-legendary",
    tokenId: 43,
    assetSymbol: "POLKADOT",
    name: "Relay Chain Sovereign",
    subtitle: "Heterogeneous Sharding Core",
    category: "Infrastructure",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 152,
    baseDef: 160,
    baseSpd: 115,
    currentAtk: 152,
    currentDef: 160,
    currentSpd: 115,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Pooled shared security powering dozens of specialized parachains concurrently.",
    skill: { name: "Parachain Cross-Consensus", description: "Deals 2.0x damage and heals all active allies by 30 HP.", manaCost: 35, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 12,
    owner: "0x71C...Demo",
    sparkline: [4.15, 4.20, 4.24, 4.28, 4.30]
  },
  {
    id: "card-polkadot-epic",
    tokenId: 44,
    assetSymbol: "POLKADOT",
    name: "Parathread Nomad",
    subtitle: "Pay-As-You-Go Validator",
    category: "Infrastructure",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 126,
    baseDef: 135,
    baseSpd: 130,
    currentAtk: 126,
    currentDef: 135,
    currentSpd: 130,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Dynamic block space allocation for cost-efficient decentralized computation.",
    skill: { name: "Blockspace Auction", description: "Steals 15 mana and reduces next skill cost by 10.", manaCost: 20, type: "drain", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 14,
    owner: "0x71C...Demo",
    sparkline: [4.18, 4.22, 4.25, 4.28, 4.30]
  },
  {
    id: "card-cosmos-legendary",
    tokenId: 45,
    assetSymbol: "COSMOS",
    name: "Tendermint Starship",
    subtitle: "The Internet of Blockchains",
    category: "Infrastructure",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 150,
    baseDef: 152,
    baseSpd: 128,
    currentAtk: 150,
    currentDef: 152,
    currentSpd: 128,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Sovereign application chains connected seamlessly through Inter-Blockchain Communication (IBC).",
    skill: { name: "IBC Packet Warp", description: "Strikes target with 2.1x ATK and redistributes 20 mana to allies.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 10,
    owner: "0x71C...Demo",
    sparkline: [4.60, 4.68, 4.72, 4.77, 4.80]
  },
  {
    id: "card-cosmos-epic",
    tokenId: 46,
    assetSymbol: "COSMOS",
    name: "Osmosis Alchemist",
    subtitle: "Superfluid Staking Sorcerer",
    category: "DeFi",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 132,
    baseDef: 124,
    baseSpd: 135,
    currentAtk: 132,
    currentDef: 124,
    currentSpd: 135,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Compounds yield across dozens of cross-chain pools with superfluid mechanics.",
    skill: { name: "Superfluid Surge", description: "Boosts team ATK and SPD by 20% for 2 turns.", manaCost: 25, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 12,
    owner: "0x71C...Demo",
    sparkline: [4.65, 4.70, 4.74, 4.78, 4.80]
  },
  {
    id: "card-aptos-legendary",
    tokenId: 47,
    assetSymbol: "APTOS",
    name: "Block-STM Hyperthreader",
    subtitle: "Speculative Concurrency Engine",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 160,
    baseDef: 135,
    baseSpd: 160,
    currentAtk: 160,
    currentDef: 135,
    currentSpd: 160,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Executes transactions speculatively in parallel and re-validates automatically on conflicts.",
    skill: { name: "Speculative Rush", description: "Delivers 2.3x ATK damage with high crit probability.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 6,
    owner: "0x71C...Demo",
    sparkline: [6.45, 6.58, 6.69, 6.78, 6.85]
  },
  {
    id: "card-aptos-epic",
    tokenId: 48,
    assetSymbol: "APTOS",
    name: "Move Language Sentinel",
    subtitle: "Resource Safety Sovereign",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 132,
    baseDef: 136,
    baseSpd: 132,
    currentAtk: 132,
    currentDef: 136,
    currentSpd: 132,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Assets as first-class resources that can never be copied or dropped by faulty bytecode.",
    skill: { name: "Resource Lock", description: "Silences enemy skills for 1 turn and inflicts 1.2x damage.", manaCost: 25, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 8,
    owner: "0x71C...Demo",
    sparkline: [6.50, 6.62, 6.71, 6.80, 6.85]
  },
  {
    id: "card-ton-legendary",
    tokenId: 49,
    assetSymbol: "TON",
    name: "Telegram Open Network Archon",
    subtitle: "900M User Gateway",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 162,
    baseDef: 145,
    baseSpd: 145,
    currentAtk: 162,
    currentDef: 145,
    currentSpd: 145,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Native crypto rails powering mini-apps, wallet bots, and peer-to-peer microtransactions across Telegram.",
    skill: { name: "Viral Mini-App", description: "Deals 2.2x damage and drains 30 mana from opponent team.", manaCost: 35, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [4.80, 4.92, 5.02, 5.10, 5.15]
  },
  {
    id: "card-ton-epic",
    tokenId: 50,
    assetSymbol: "TON",
    name: "Fragment Username Broker",
    subtitle: "Decentralized Handle Sovereign",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 134,
    baseDef: 130,
    baseSpd: 136,
    currentAtk: 134,
    currentDef: 130,
    currentSpd: 136,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Facilitates high-value auction settlement for digital identities and virtual phone numbers.",
    skill: { name: "Auction Bid Wave", description: "Steals 20 Shield and deals 1.5x ATK.", manaCost: 25, type: "attack", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 5,
    owner: "0x71C...Demo",
    sparkline: [4.85, 4.95, 5.05, 5.11, 5.15]
  },
  {
    id: "card-tron-legendary",
    tokenId: 51,
    assetSymbol: "TRON",
    name: "USDT Settlement Titan",
    subtitle: "Global Dollar Backbone",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 154,
    baseDef: 165,
    baseSpd: 120,
    currentAtk: 154,
    currentDef: 165,
    currentSpd: 120,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Transfers over $50 billion in tether volume every single day across emerging markets.",
    skill: { name: "Tether Flood", description: "Deals 2.0x damage and restores 40 HP to all allies.", manaCost: 35, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 9,
    owner: "0x71C...Demo",
    sparkline: [0.142, 0.145, 0.147, 0.149, 0.15]
  },
  {
    id: "card-tron-rare",
    tokenId: 52,
    assetSymbol: "TRON",
    name: "Tron Energy Burner",
    subtitle: "Zero-Fee Fee Staker",
    category: "L1",
    rarity: "Rare",
    foilType: "Standard",
    baseAtk: 118,
    baseDef: 130,
    baseSpd: 122,
    currentAtk: 118,
    currentDef: 130,
    currentSpd: 122,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Freezes TRX to rent energy and bandwidth for zero-fee transfer settlement.",
    skill: { name: "Zero-Fee Burst", description: "Next skill costs 0 mana; deals 1.3x damage.", manaCost: 15, type: "buff", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 14,
    owner: "0x71C...Demo",
    sparkline: [0.144, 0.146, 0.148, 0.149, 0.15]
  },
  {
    id: "card-ripple-legendary",
    tokenId: 53,
    assetSymbol: "RIPPLE",
    name: "XRPL Ledger Sentinel",
    subtitle: "Enterprise Liquidity Sovereign",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 152,
    baseDef: 168,
    baseSpd: 115,
    currentAtk: 152,
    currentDef: 168,
    currentSpd: 115,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Instant cross-border gross settlement protocol powering institutional liquidity rails.",
    skill: { name: "ODL Instant Settlement", description: "Bypasses enemy defenses and strikes for 2.1x ATK.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 11,
    owner: "0x71C...Demo",
    sparkline: [0.54, 0.55, 0.56, 0.57, 0.58]
  },
  {
    id: "card-ripple-epic",
    tokenId: 54,
    assetSymbol: "RIPPLE",
    name: "Interledger Navigator",
    subtitle: "Universal Payment Rail",
    category: "Infrastructure",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 128,
    baseDef: 145,
    baseSpd: 125,
    currentAtk: 128,
    currentDef: 145,
    currentSpd: 125,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Packetizes value transfers across heterogeneous payment networks.",
    skill: { name: "Pathfinding Protocol", description: "Finds the optimal path: deals 1.6x damage and steals 15 Shield.", manaCost: 25, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 15,
    owner: "0x71C...Demo",
    sparkline: [0.55, 0.56, 0.568, 0.575, 0.58]
  },
  {
    id: "card-fantom-legendary",
    tokenId: 55,
    assetSymbol: "FANTOM",
    name: "Sonic Executioner",
    subtitle: "Sub-Second DAG Apex",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 164,
    baseDef: 130,
    baseSpd: 175,
    currentAtk: 164,
    currentDef: 130,
    currentSpd: 175,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "10,000 TPS with sub-second finality on an asynchronous Directed Acyclic Graph.",
    skill: { name: "Sonic Boom", description: "Strikes with 2.4x ATK and stuns enemy for 1 turn.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 4,
    owner: "0x71C...Demo",
    sparkline: [0.44, 0.45, 0.46, 0.47, 0.48]
  },
  {
    id: "card-fantom-epic",
    tokenId: 56,
    assetSymbol: "FANTOM",
    name: "Lachesis Opera Maestro",
    subtitle: "aBFT Consensus Virtuoso",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 136,
    baseDef: 122,
    baseSpd: 150,
    currentAtk: 136,
    currentDef: 122,
    currentSpd: 150,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Processes events in parallel DAG vertices without waiting for rigid block intervals.",
    skill: { name: "DAG Event Synthesis", description: "Attacks twice for 80% damage each; boosts SPD by 25%.", manaCost: 25, type: "attack", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 7,
    owner: "0x71C...Demo",
    sparkline: [0.45, 0.46, 0.465, 0.475, 0.48]
  },
  {
    id: "card-robinhood-legendary",
    tokenId: 57,
    assetSymbol: "ROBINHOOD",
    name: "Sherwood Sovereign",
    subtitle: "Zero-Fee Liquidity Apex",
    category: "DeFi",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 170,
    baseDef: 155,
    baseSpd: 145,
    currentAtk: 170,
    currentDef: 155,
    currentSpd: 145,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Democratizing financial power for millions with commission-free atomic order routing.",
    skill: { name: "Sherwood Solar Arrow", description: "Fires a blazing solar volley for 175 Fire damage and sets the target ablaze (Burn for 2 turns).", manaCost: 35, type: "burn", element: "fire", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 2,
    owner: "0x71C...Demo",
    sparkline: [19.8, 20.2, 20.7, 21.1, 21.4]
  },
  {
    id: "card-robinhood-epic",
    tokenId: 58,
    assetSymbol: "ROBINHOOD",
    name: "Instant Settlement Router",
    subtitle: "Commission-Free Engine",
    category: "DeFi",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 138,
    baseDef: 132,
    baseSpd: 150,
    currentAtk: 138,
    currentDef: 132,
    currentSpd: 150,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Instant buying power and continuous dividend yield streaming straight to on-chain accounts.",
    skill: { name: "Zero-Fee Execution", description: "Takes an immediate extra action with 0 mana cost.", manaCost: 25, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 4,
    owner: "0x71C...Demo",
    sparkline: [20.0, 20.4, 20.8, 21.2, 21.4]
  },
  {
    id: "card-zksync-legendary",
    tokenId: 59,
    assetSymbol: "ZKSYNC",
    name: "Boojum Prover Apex",
    subtitle: "Hyperchain Zero-Knowledge Sovereign",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 160,
    baseDef: 158,
    baseSpd: 142,
    currentAtk: 160,
    currentDef: 158,
    currentSpd: 142,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Generates recursive STARK proofs at lightning speed running on standard consumer hardware.",
    skill: { name: "Hyperchain Recursion", description: "Deals 2.2x damage and grants 40 Shield to all active allies.", manaCost: 35, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [0.134, 0.137, 0.139, 0.141, 0.142]
  },
  {
    id: "card-zksync-epic",
    tokenId: 60,
    assetSymbol: "ZKSYNC",
    name: "ZK Credo Vanguard",
    subtitle: "Account Abstraction Archon",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 135,
    baseDef: 135,
    baseSpd: 140,
    currentAtk: 135,
    currentDef: 135,
    currentSpd: 140,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Native account abstraction enabling paymasters and multisig security natively at protocol level.",
    skill: { name: "Native Paymaster", description: "Bypasses all mana costs for the next 2 turns.", manaCost: 25, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 6,
    owner: "0x71C...Demo",
    sparkline: [0.135, 0.138, 0.140, 0.141, 0.142]
  },
  {
    id: "card-monad-legendary",
    tokenId: 61,
    assetSymbol: "MONAD",
    name: "Parallel EVM Singularity",
    subtitle: "10,000 TPS Pipelined Executioner",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 172,
    baseDef: 135,
    baseSpd: 180,
    currentAtk: 172,
    currentDef: 135,
    currentSpd: 180,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Superscalar pipelining and custom MonadDB delivering 10,000 true EVM transactions per second.",
    skill: { name: "Parallel Voltage Storm", description: "Attacks with 160 Electric damage, inflicting Shock (-50% SPD, 35% recoil fizzle) for 2 turns.", manaCost: 35, type: "shock", element: "electric", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 1,
    owner: "0x71C...Demo",
    sparkline: [10.5, 11.2, 11.9, 12.4, 12.8]
  },
  {
    id: "card-monad-epic",
    tokenId: 62,
    assetSymbol: "MONAD",
    name: "MonadDB Titan",
    subtitle: "Custom Asynchronous Storage",
    category: "Infrastructure",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 142,
    baseDef: 140,
    baseSpd: 165,
    currentAtk: 142,
    currentDef: 140,
    currentSpd: 165,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Eliminates state access bottlenecks through native async disk I/O and parallel Merkle trie hashing.",
    skill: { name: "Parallel Voltage Shock", description: "Discharges 155 Electric damage across parallel threads, shocking the target for 2 turns.", manaCost: 30, type: "shock", element: "electric", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [10.8, 11.4, 12.0, 12.5, 12.8]
  },
  {
    id: "card-apechain-legendary",
    tokenId: 63,
    assetSymbol: "APECHAIN",
    name: "ApeChain Nexus",
    subtitle: "Arbitrum Orbit Yuga Sovereign",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 168,
    baseDef: 140,
    baseSpd: 155,
    currentAtk: 168,
    currentDef: 140,
    currentSpd: 155,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Dedicated consumer layer powered by ApeCoin native gas for decentralized culture and gaming.",
    skill: { name: "Banana Split Shock", description: "Deals 2.3x ATK damage and confuses opponent for 1 turn.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 1,
    owner: "0x71C...Demo",
    sparkline: [0.65, 0.68, 0.71, 0.73, 0.75]
  },
  {
    id: "card-apechain-epic",
    tokenId: 64,
    assetSymbol: "APECHAIN",
    name: "Curtis Vanguard",
    subtitle: "Ape Orbit Testnet Raider",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 135,
    baseDef: 130,
    baseSpd: 145,
    currentAtk: 135,
    currentDef: 130,
    currentSpd: 145,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Fast settlement and zero friction for creators across the Bored Ape ecosystem.",
    skill: { name: "Yuga State Burst", description: "Boosts team ATK by 25% and restores 20 energy.", manaCost: 25, type: "buff", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 2,
    owner: "0x71C...Demo",
    sparkline: [0.67, 0.70, 0.72, 0.74, 0.75]
  },
  {
    id: "card-gnosis-legendary",
    tokenId: 65,
    assetSymbol: "GNOSIS",
    name: "Gnosis Safe Citadel",
    subtitle: "Multi-Sig Security Fortress",
    category: "Infrastructure",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 150,
    baseDef: 180,
    baseSpd: 110,
    currentAtk: 150,
    currentDef: 180,
    currentSpd: 110,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Protecting hundreds of billions in digital assets through modular smart account validation.",
    skill: { name: "Multi-Sig Fortification", description: "Grants 60 Shield and reflects 35% damage back to attackers.", manaCost: 35, type: "shield", cooldownTurns: 3 },
    mintedAt: Date.now() - 86400000 * 5,
    owner: "0x71C...Demo",
    sparkline: [165, 168, 170, 171, 172.5]
  },
  {
    id: "card-gnosis-epic",
    tokenId: 66,
    assetSymbol: "GNOSIS",
    name: "CoW Swap Arbitrageur",
    subtitle: "MEV-Protected Batch Auctioneer",
    category: "DeFi",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 140,
    baseDef: 145,
    baseSpd: 135,
    currentAtk: 140,
    currentDef: 145,
    currentSpd: 135,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Eliminates sandwich attacks and front-running via coincidence of wants batch auctions.",
    skill: { name: "Coincidence of Wants", description: "Steals 25 Shield and redirects enemy turn priority.", manaCost: 25, type: "drain", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 7,
    owner: "0x71C...Demo",
    sparkline: [166, 169, 170.5, 171.8, 172.5]
  },
  {
    id: "card-linea-legendary",
    tokenId: 67,
    assetSymbol: "LINEA",
    name: "Linea zkEVM Surge",
    subtitle: "Consensys Prover Core",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 164,
    baseDef: 152,
    baseSpd: 148,
    currentAtk: 164,
    currentDef: 152,
    currentSpd: 148,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Native EVM equivalence proving zero-knowledge proofs seamlessly with MetaMask ecosystem.",
    skill: { name: "Consensys Shaper", description: "Bypasses 50% enemy defense and strikes with 2.2x ATK.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 2,
    owner: "0x71C...Demo",
    sparkline: [1.70, 1.74, 1.78, 1.82, 1.85]
  },
  {
    id: "card-linea-epic",
    tokenId: 68,
    assetSymbol: "LINEA",
    name: "Vortex State Prover",
    subtitle: "Recursive Lattice Compiler",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 136,
    baseDef: 134,
    baseSpd: 142,
    currentAtk: 136,
    currentDef: 134,
    currentSpd: 142,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Compresses execution trace logs down to cryptographic succinctness at low gas fees.",
    skill: { name: "Vortex Lattice", description: "Grants 35 Shield and delivers 1.4x counter-attack.", manaCost: 25, type: "shield", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 4,
    owner: "0x71C...Demo",
    sparkline: [1.72, 1.76, 1.80, 1.83, 1.85]
  },
  {
    id: "card-worldchain-legendary",
    tokenId: 69,
    assetSymbol: "WORLDCHAIN",
    name: "World ID Gatekeeper",
    subtitle: "Proof-of-Humanity Sovereign",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 160,
    baseDef: 160,
    baseSpd: 140,
    currentAtk: 160,
    currentDef: 160,
    currentSpd: 140,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Prioritizes blockspace for verified humans over bots on the Optimism Superchain.",
    skill: { name: "Iris Biometric Proof", description: "Negates enemy bot buffs and deals 2.1x damage.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 3,
    owner: "0x71C...Demo",
    sparkline: [1.80, 1.84, 1.88, 1.92, 1.95]
  },
  {
    id: "card-worldchain-epic",
    tokenId: 70,
    assetSymbol: "WORLDCHAIN",
    name: "Orb Verifier Sentry",
    subtitle: "Priority Blockspace Dispatcher",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 132,
    baseDef: 140,
    baseSpd: 138,
    currentAtk: 132,
    currentDef: 140,
    currentSpd: 138,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Allocates free gas allowances directly to verified unique humans across 160 countries.",
    skill: { name: "Human Gas Priority", description: "Restores 30 Mana and gives entire team +15 SPD.", manaCost: 20, type: "buff", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 5,
    owner: "0x71C...Demo",
    sparkline: [1.82, 1.86, 1.89, 1.93, 1.95]
  },
  {
    id: "card-hedera-legendary",
    tokenId: 71,
    assetSymbol: "HEDERA",
    name: "Hashgraph Gossip Core",
    subtitle: "Asynchronous Byzantine Apex",
    category: "L1",
    rarity: "Legendary",
    foilType: "GoldFoil",
    baseAtk: 166,
    baseDef: 158,
    baseSpd: 165,
    currentAtk: 166,
    currentDef: 158,
    currentSpd: 165,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "10,000+ TPS fair-ordered consensus validated by leading global enterprise council members.",
    skill: { name: "Gossip About Gossip", description: "Strikes with 2.3x ATK and gains 100% turn meter boost.", manaCost: 35, type: "attack", cooldownTurns: 2 },
    mintedAt: Date.now() - 86400000 * 6,
    owner: "0x71C...Demo",
    sparkline: [0.050, 0.051, 0.052, 0.053, 0.054]
  },
  {
    id: "card-hedera-epic",
    tokenId: 72,
    assetSymbol: "HEDERA",
    name: "HBAR Velocity Sentinel",
    subtitle: "Fair-Ordering Consensus Arbiter",
    category: "L1",
    rarity: "Epic",
    foilType: "Holo",
    baseAtk: 135,
    baseDef: 136,
    baseSpd: 160,
    currentAtk: 135,
    currentDef: 136,
    currentSpd: 160,
    statMultiplier: 1.0,
    deltaPercent: 0,
    trend: "neutral",
    flavorText: "Microsecond timestamping without miners, proof-of-work wasted energy, or MEV reordering.",
    skill: { name: "Virtual Voting Strike", description: "Attacks twice for 75% damage and cleanses all debuffs.", manaCost: 25, type: "attack", cooldownTurns: 1 },
    mintedAt: Date.now() - 86400000 * 8,
    owner: "0x71C...Demo",
    sparkline: [0.051, 0.052, 0.053, 0.0535, 0.054]
  }
];

// Target list of user-requested EVM and supported chains
export const EVM_CHAIN_SYMBOLS: AssetSymbol[] = [
  "ROBINHOOD",
  "ETH",
  "ARBITRUM",
  "OPTIMISM",
  "BASE",
  "AVAX",
  "POLYGON",
  "BNB",
  "ZKSYNC",
  "MONAD",
  "COSMOS",
  "APECHAIN",
  "GNOSIS",
  "LINEA",
  "TON",
  "WORLDCHAIN",
  "HEDERA"
];

// Curated EVM-only catalog of cards for DriftWall and gameplay
export const EVM_CARD_CATALOG: Card[] = BASE_CARD_CATALOG.filter((c) =>
  EVM_CHAIN_SYMBOLS.includes(c.assetSymbol)
);

export const INITIAL_USER_COLLECTION: Card[] = [
  BASE_CARD_CATALOG.find((c) => c.assetSymbol === "ROBINHOOD") || BASE_CARD_CATALOG[0],
  BASE_CARD_CATALOG[1], // ETH Legendary
  BASE_CARD_CATALOG.find((c) => c.assetSymbol === "ARBITRUM") || BASE_CARD_CATALOG[2],
  BASE_CARD_CATALOG.find((c) => c.assetSymbol === "OPTIMISM") || BASE_CARD_CATALOG[3],
  BASE_CARD_CATALOG.find((c) => c.assetSymbol === "BASE") || BASE_CARD_CATALOG[4],
  BASE_CARD_CATALOG.find((c) => c.assetSymbol === "MONAD") || BASE_CARD_CATALOG[5]
];
