// Automatically generated by contracts/deploy.ts
// Network: Sepolia Testnet (Chain ID: 11155111)

export const CONTRACT_CONFIG = {
  chainId: 11155111,
  chainName: "Ethereum Sepolia",
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorerUrl: "https://sepolia.etherscan.io",
  cardContract: "0x209139a7c49a2ea834daf5ff496008ea02b2fbba" as const,
  prizePoolContract: "0xdb2db0f2bd83cfb8d5f1db480caf661978624f56" as const,
  packContract: "0x1dc2656a699c1bf6d827c555c994f5fd89e1ff75" as const,
  marketplaceContract: "0xb20655cb8160350ece1897a86ebbf832b4c26851" as const
};

export const CONTRACT_ADDRESSES = {
  ...CONTRACT_CONFIG
};

export function getExplorerTxUrl(txHash: string): string {
  return `${CONTRACT_CONFIG.explorerUrl}/tx/${txHash}`;
}

export function getExplorerAddressUrl(address: string): string {
  return `${CONTRACT_CONFIG.explorerUrl}/address/${address}`;
}
